sudo: required
addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/jonathonf/vim/ubuntu trusty main'
    travis_apt_options: --allow-unauthenticated
    packages:
      - make
      - gcc
      - git
      - curl
      - zsh
      - tmux
      - vim
      - rxvt-unicode

language: bash
script: bash setup.sh
